steps:
    - name: gradle:7.3.1-jdk8
      entrypoint: gradle
      args: ['test']
    - name: gradle:7.3.1-jdk8
      args: ['jib']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: ['gcloud', 'run', 'services', 'update', 'jot-it-down', 'gcr.io/web-apps-327720/jot-it-down:latest']
