steps:
    - name: 'gradle:7.3-jdk8'
      entrypoint: 'gradle'
      args: ['test']
      id: 'Test'
    - name: 'gradle:7.3-jdk8'
      entrypoint: 'gradle'
      secretEnv: ['USERNAME', 'PASSWORD']
      args: ['jib', '-Pgcloud_username=$$USERNAME', '-Pgcloud_password=$$PASSWORD']
      id: 'Build & Upload Image'
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args: ['gcloud', 'run', 'services', 'update', 'jot-it-down', '--image', 'gcr.io/web-apps-327720/jot-it-down:latest']
      id: 'Deployment'
availableSecrets:
    secretManager:
        - versionName: projects/web-apps-327720/secrets/GCLOUD_USERNAME/versions/1
          env: 'USERNAME'
        - versionName: projects/web-apps-327720/secrets/GCLOUD_PASSWORD/versions/1
          env: 'PASSWORD'
